In [5]:
import numpy as np

In [6]:
import numpy as np

a = np.array([[1, 2, 4], [1, 3, 5]])
a2 = a.view()   #shallow copy
a3 = a.copy()   #deep copy

a2[0][1] = 111
display(a)

a3[0][1] = 101
display(a)

array([[  1, 111,   4],
       [  1,   3,   5]])

array([[  1, 111,   4],
       [  1,   3,   5]])

In [7]:
import numpy as np

list = [1, 3, 5]
a1 = np.array(list)

a2 = np.array([2, 4, 6])
a3 = np.array(range(1, 11))

a4 = np.array((7, 11, 101, 555))

a5 = np.array([3 * x for x in range(1, 6)])

print(a1, a2, a3, a4, a5, sep='\n\n')

[1 3 5]

[2 4 6]

[ 1  2  3  4  5  6  7  8  9 10]

[  7  11 101 555]

[ 3  6  9 12 15]


In [8]:
import numpy as np

a = np.array([1, 2.5, 0])

b = np.array([1, True, 'Three', 4.5])

c = np.array([False, True, 10])

print(a, b, c, sep='\n\n')

#print(a.dtype, b.dtype, c.dtype, sep='\n')

[1.  2.5 0. ]

['1' 'True' 'Three' '4.5']

[ 0  1 10]


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

b = np.array([1.2, 3.141, 5.55, 9.99], dtype='i')

c = np.array([-5, -1, 0, 1, 1.5, 10], dtype=np.bool)

print(a, b, c, sep='\n\n')

[1. 2. 3. 4. 5.]

[1 3 5 9]

[ True  True False  True  True  True]


C:\Users\samit\AppData\Local\Temp\ipykernel_24600\239680300.py:7: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.array([-5, -1, 0, 1, 1.5, 10], dtype=np.bool)


In [10]:
import numpy as np

a = np.arange(1, 10)
b = np.arange(1, 10, 2)
c = np.arange(1, 10, 2.5)
d = np.arange(10, 1, -3)
e = np.arange(-10.5, 5.5, 3.5)
f = np.arange(100, 1, 10)

print(a, b, c, d, e, f, sep='\n\n')

[1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]

[1.  3.5 6.  8.5]

[10  7  4]

[-10.5  -7.   -3.5   0.    3.5]

[]


In [11]:
import numpy as np

a1 = np.linspace(1, 10, 4)
a2 = np.linspace(1, 10, 6)
a3 = np.linspace(1, 10, 4, dtype=int)
a4 = np.linspace(-10, 10, 6)
a5 = np.linspace(10.5, 1.5, 5)

print(a1, a2, a3, a4, a5, sep='\n\n')

[ 1.  4.  7. 10.]

[ 1.   2.8  4.6  6.4  8.2 10. ]

[ 1  4  7 10]

[-10.  -6.  -2.   2.   6.  10.]

[10.5   8.25  6.    3.75  1.5 ]
